### ISSUE TITLE
Can I use proxy mode?

### ISSUE THREAD

**Issue by writer0713** [Thoroldvix/youtube-transcript-api#23]
On python version, there is a proxy option.
Does this library support proxy mode?
Or, is there any other solutions to use proxy?

I ask this question, because it doesn’t work on oracle cloud.

**Comment by Thoroldvix** [comment]
Hey, there are no proxy support out of the box, but you can add it by implementing your own  YoutubeClient, you can check how to do it [here](https://github.com/Thoroldvix/youtube-transcript-api#youtubeclient-customization)
