### ISSUE TITLE
My App in Android crashes.

### ISSUE THREAD

**Issue by Morfonio** [Thoroldvix/youtube-transcript-api#29]
What happens is that when testing the operation of this line of code

// Create a new default YoutubeTranscriptApi instance
`YoutubeTranscriptApi youtubeTranscriptApi = TranscriptApiFactory.createDefault();`

My application closes when going through there.

Why might this be happening?

**Comment by Thoroldvix** [comment]
Hi, can you post screenshots of the error you are getting?

**Comment by Morfonio** [comment]
Yes I attached a screenshot.
![Error Youtube Transcrip 3](https://github.com/user-attachments/assets/b77d2449-67bb-4220-ad7d-ffa249438034)

**Comment by Thoroldvix** [comment]
> Yes I attached a screenshot. ![Error Youtube Transcrip 3](https://private-user-images.githubusercontent.com/20160412/386998841-b77d2449-67bb-4220-ad7d-ffa249438034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzY2NTQsIm5iZiI6MTczMTg3NjM1NCwicGF0aCI6Ii8yMDE2MDQxMi8zODY5OTg4NDEtYjc3ZDI0NDktNjdiYi00MjIwLWFkN2QtZmZhMjQ5NDM4MDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDIwNDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YzdjMjExOWZjZDBkYjEzZWNmOThkNTAyYTU0ODE4YzA2YWI4ODc4N2U1ZGM3MWY1YTc5MmEwYWVkOTEwNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0aODP9MsmbUFKno1-WuXMv9BjpKlO6MrwdX9YLjiNJ0)

This library uses java 11 HttpClient for making network calls by default, it is not included in android sdk. You can implement your own YoutubeClient, which can use any Http client you like. You can see how to do it [here](https://github.com/Thoroldvix/youtube-transcript-api/issues/22)

**Comment by Morfonio** [comment]
When I try to implement the OkHttpYoutubeClient class I get many errors. 

![Error Youtube Transcrip 4](https://github.com/user-attachments/assets/8e333acb-9595-4d90-8188-a2588153163f)

**Comment by Thoroldvix** [comment]
OkHttp is a 3rd party dependency, so you will need to import it in your build.gradle.kts. Check their documentation for more info, https://square.github.io/okhttp/#releases

**Comment by Morfonio** [comment]
Thanks, I've been able to eliminate most of the errors now, but I still have 1 final error left:

![Error Youtube Transcrip 5](https://github.com/user-attachments/assets/502a5367-cef7-4fce-bc4e-44b0b72b419c)

![Error Youtube Transcrip 6](https://github.com/user-attachments/assets/87699912-aa93-4d6d-8d89-518645860662)

**Comment by Thoroldvix** [comment]
Example implementation uses dependency injection, if you want to instantiate OkHttpClient directly in constructor you need to add new or replace current constructor.  With this:

```java
public OkHttpYoutubeClient() {
      this.client = new OkHttpClient();
}
```

This errors are not really related to the library itself, so i will stop troubleshooting them for you. You will need to learn how to google. Good luck 🙂

**Comment by Morfonio** [comment]
Thank you very much and I apologize.
